"""add gateway_payment_id to payments

Revision ID: 84fcdcce4ab8
Revises: e5d2e8bcb6c9
Create Date: 2026-09-13 07:53:26.289572

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84fcdcce4ab8'
down_revision = 'e5d2e8bcb6c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gateway_payment_id', sa.String(length=64), nullable=True))
        batch_op.create_index(batch_op.f('ix_payments_gateway_payment_id'), ['gateway_payment_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payments_gateway_payment_id'))
        batch_op.drop_column('gateway_payment_id')

    # ### end Alembic commands ###
