"""Add indexes on events and bookings filter/join columns

Revision ID: e5d2e8bcb6c9
Revises: 6511ee91ff71
Create Date: 2026-09-04 06:47:47.103167

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5d2e8bcb6c9'
down_revision = '6511ee91ff71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bookings_event_id'), ['event_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bookings_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_events_city'), ['city'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_events_user_id'))
        batch_op.drop_index(batch_op.f('ix_events_date'))
        batch_op.drop_index(batch_op.f('ix_events_city'))

    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bookings_user_id'))
        batch_op.drop_index(batch_op.f('ix_bookings_event_id'))

    # ### end Alembic commands ###
